alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias dotfiles="cd ~/.dotfiles"
alias config="cd ~/.dotfiles/config"
alias tms="tmux-sessionizer"

alias gs="git status"
alias glo="git log --oneline"
alias ga="git add"
alias gu="git restore --stage"
alias gcm="git commit -m"
alias gp="git push"
alias gco="git-branch-previewer"
alias gdf="git diff"

alias ls="exa -la --no-user --no-filesize --no-time"
