#!/bin/sh

mkdir -p ~/.config ~/.local/bin

pkg update -y && pkg upgrade -y
pkg install -y zsh man which eza bat git git-delta neovim lua-language-server ripgrep fd fzf

# Clone dotfiles if doesn't exist
[ ! -d ~/.dotfiles ] && $PREFIX/bin/git clone --depth 1 https://github.com/geloman-likes-rust/termux ~/.dotfiles

# Delete & replace default termux config
[ -d ~/.termux ] && rm -rdf ~/.termux && ln -s ~/.dotfiles/termux ~/.termux

# Symlink gitconfig
[ -f ~/.gitconfig ] && mv ~/.gitconfig ~/.gitconfig.bak && ln -s ~/.dotfiles/git/.gitconfig ~/.gitconfig

# Symlink neovim config
[ ! -d ~/.config/nvim ] && ln -s ~/.dotfiles/nvim ~/.config

# Symlink tmux config
[ ! -f ~/.tmux.conf ] && ln -s ~/.dotfiles/tmux/.tmux.conf ~/.tmux.conf

# Symlink zshrc
[ -f ~/.zshrc ] && mv ~/.zshrc ~/.zshrc.bak && ln -s ~/.dotfiles/zsh/.zshrc ~/.zshrc

# Symlink bash configs
[ -f ~/.bashrc ] && mv ~/.bashrc ~/.bashrc.bak && ln -s ~/.dotfiles/bash/.bashrc ~/.bashrc
[ -f ~/.inputrc ] && mv ~/.inputrc ~/.inputrc.bak; ln -s ~/.dotfiles/bash/.inputrc ~/.inputrc

# Install tmux plugin manager
[ ! -d ~/.tmux/plugins/tpm ] && $PREFIX/bin/git --depth 1 clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
[ -n "$(command -v tmux)" ] && TMUX_PLUGIN_MANAGER_PATH="~/.tmux/plugins/" tmux -c '~/.tmux/plugins/tpm/bindings/install_plugins'

# Install neovim plugins
$PREFIX/bin/nvim --headless "+Lazy! restore" +qa
